source "https://rubygems.org"

gem "bourbon", "~> 5.0.0"
gem "middleman", "~> 4.0"
gem "middleman-autoprefixer"
gem "middleman-blog"
gem "middleman-deploy", "= 2.0.0.pre.alpha"
gem "middleman-livereload"
gem "middleman-sprockets", "~> 4.1.0"
gem "neat", "~> 1.7.0"
